name: Starter Udacity

on: 
  push:
    branches: [main , master]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: Install dependencies
      run: pip install -U dvc[gdrive] pydrive2
           dvc pull
      env: 
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
