name: Starter Udacity

on: 
  push:
    branches: [main , master]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    
    steps:
    - uses: actions/checkout@v2
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: python -m pip install pytest flake8 numpy==1.23.5 pandas==1.5.2 fastapi requests httpx scikit-learn==1.1.3 dvc dvc[gdrive] pydrive2
           pip install -e starter

    - name: run flake
      run: flake8 --ignore=E501,W503,W501 starter/sanitycheck.py
    
    - name: dvc pull
      env: 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: dvc pull

    - name: run pytest
      run: pytest